language: java
os: linux
jdk: openjdk8

branches:
  except:
    - gh-pages

deploy:
  - provider: releases
    api_key:
      secure: q8vk0KVjdq6el1qlecI9cHJ4LiX+JPr/MEfMM92e76waNZ+RLSpO3cX3ly9byY4UWModl247FYNicYnxGADMYdHMsXSatcGmZ9Uu2+vRsgvI61zlOh/ckMJvjoj7gYgfZZFNULiNNHF3mA785Wdu7Mb2XIkrwPws9QEX/VN2W/nAlkEOGhtvL8IsIFy0Hkr15EY/M89jfityxsuDPZYSxJlU4MaIeU3olUTPP8J44TaxMUhLrH5HLo3iGPvelmTCie3r3mV9P7lY05iNnBwH4vJwmRjRDGQZlfNg4qpSPJHu9vNgHdvqxRCOl0b/U5aaS1K2Kk9PzRDgorsDss3mktqPyspySvODhLOz52cAViBaig+qWnwtcnz5DAtGmE1Xyy6PLNImm374Zy2WUFkm9Qd5mT7N10bCFoiiISd2FRA3Pd+6GU/0GpvBQyjOjU74eqhkZBheTenSp4drsWcylVuia8feD7IUt1HWlSXVsrWAhD8eEY2bZPN6hwqzq/ciiNmlsbA2IBcK6XzLwzdKve8IDwySIxNwjtPbzbR8eAX03n/g07Bmk1x2fxcuS5N+u44IhIvuEMlhN5PjeaGM7LPgFJb2ee7wYZJfQ2GXPTz8GEuuyMsGlc/xnDbJU2UPaH7WCD8/rHvfRqTmjvqJWEMiv90t0MjF5gXqyUebj4U=
    skip_cleanup: true
    file_glob: true
    file: build/libs/prometheus-kafka-writer-*-all.jar
    draft: true
    on:
      tags: true
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      branch: master
      tags: true
